### ISSUE TITLE
Add a Bootstrap's NavBar

### ISSUE THREAD

**Issue by CarmelSoftware** [CarmelSoftware/AngularJS_OData_HTTPPATCH#4]
A Bootstrap's NavBar must to be added to the
Branch "Twitter Bootstrap":
file name: /Contents/Navbar.html

**Comment by CarmelSchvartzman** [comment]
Added Bootstrap NavBar to Branch "Twitter Bootstrap"
fixing #5

**Comment by CarmelSoftware** [comment]
OK
